server:
  port: 9999
  context-path: /
  tomcat:
    uri-encoding: UTF-8

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.193.131:3306/news?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Lishen2018@
#    password: XXX
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: true

    
lucenePath: C://lucene

articleImageFilePath: D://articleImages/

userImageFilePath: D://userImages/

#lucenePath: /home/lucene

#articleImageFilePath: /home/articleImages/

#userImageFilePath: /home/userImages/